### PR TITLE
[UI][Louise] created new event description UI

### LINKED ISSUE #24: Update event description
As an iskolar ng bayan, I think we can do better...

### PR DESCRIPTION
**Pull request by Loweso**
@maxellmilay @arwin50 event description part idea, mostly layout for now

image
image
image

thoughts?

### CODE REVIEW

**Comment by maxellmilay** [comment]
Wow, this is really amazing @Loweso

**Comment by maxellmilay** [comment]
Is this responsive @Loweso? Kindly include mobile viewport perspective

**Comment by Loweso** [comment]
> Is this responsive @Loweso? Kindly include mobile viewport perspective

not fully responsive yet, will get back to you on it... @maxellmilay

**Comment by Loweso** [comment]
@maxellmilay @arwin50 made event section responsive, draft for now(?)

image
image

**Comment by maxellmilay** [comment]
> @maxellmilay @arwin50 made event section responsive, draft for now(?)
> 
> 
> 
> image
> 
> image
> 
> 

Can you center the image in mobile?

**Comment by Loweso** [comment]
sige try @maxellmilay

**Comment by Loweso** [comment]
@maxellmilay @arwin50 adjusted the main visual

image
image

if its ok, please run the app nlng para sure

**Review by maxellmilay — APPROVED** [review]
@Loweso LGTM :fire:

**Pull request merged**
