### PR TITLE
[UI] Booths section

### LINKED ISSUE #8: Add Booths page
Place this in the landing of booths page:

"Registrations for booths open until APRIL 23, 2024. Cosplay Crosswalk apps are open until MAY 11, 2024.

Interested in collaborating, partnering, or working with us? Email us here!

Not sure if your products or displays are suitable for our event? Check out our detailed content filtering guide!

### PR DESCRIPTION
**Pull request by Loweso**
created booth section, nonworking components (e.g. links except for of merch filter guide)

@maxellmilay @arwin50 pacheck lang nya ko uwu, edit lng ko accdngly sa inyo remarks chariz

image
image

### CODE REVIEW

**Comment by maxellmilay** [comment]
@Loweso can you add images or icons or something that will make the landing section pop better? I noticed that it is bland right now

**Comment by maxellmilay** [comment]
In addition, make the 4 button applications visible the moment the user lands in the website

**Comment by Loweso** [comment]
> @Loweso can you add images or icons or something that will make the landing section pop better? I noticed that it is bland right now

can you elaborate further? what do you mean to make the landing section pop better?

**Comment by Loweso** [comment]
> In addition, make the 4 button applications visible the moment the user lands in the website

so instead of the carousel, the booth section is the first thing that greets the user?

**Comment by maxellmilay** [comment]
> @Loweso can you add images or icons or something that will make the landing section pop better? I noticed that it is bland right It's somewhat monotonic, red and white, plus only text ra ang naa

**Comment by maxellmilay** [comment]
> > In addition, make the 4 button applications visible the moment the user lands in the website
> 
> so instead of the carousel, the booth section is the first thing that greets the user?

scratch this, I thought this was the hero section

**Comment by maxellmilay** [comment]
> @Loweso can you add images or icons or something that will make the landing section pop better? I noticed that it is bland right now

for this, can we change the color of the header or the body? since it blends together

**Comment by maxellmilay** [comment]
@Loweso Ayaw kauwaw ug implement sa imong idea or creative UI, dili man limited to texts atong components hahaha

**Comment by Loweso** [comment]
> > @Loweso can you add images or icons or something that will make the landing section pop better? I noticed that it is bland right now
> 
> for this, can we change the color of the header or the body? since it blends together

if i do that, do i adjust the colors of the other sections too? since the colors are puli2 HAHAHAHA kapuya english

**Comment by maxellmilay** [comment]
> > > @Loweso can you add images or icons or something that will make the landing section pop better? I noticed that it is bland right now
> > 
> > 
> > for this, can we change the color of the header or the body? since it blends together
> 
> if i do that, do i adjust the colors of the other sections too? since the colors are puli2 HAHAHAHA kapuya english

HAHAHAHHA, we can retain the white ones, just the ones with the color with the header

**Comment by Loweso** [comment]
I'll make new PR, dugaya nako nahuman aning react icon oi 3HRS WTF

**Pull request closed without merging**
