### PR TITLE
[Arwin][UI] hidden scrollbar at carousel card and changed sm seaside …

### PR DESCRIPTION
**Pull request by arwin50**
image

mao ni pasabot ani?

### CODE REVIEW

**Comment by maxellmilay** [comment]
@arwin50 what do you think about moving the sm seaside logo at the bottom of the date?

**Comment by arwin50** [comment]
wdym? sa carousel card? @maxellmilay

**Comment by arwin50** [comment]
image

**Review by maxellmilay — APPROVED** [review]
@arwin50 LGTM :fire:

**Pull request merged**
